const { DataTypes, Model } = require('sequelize');
const sequelize = require('../config/database');
class CourseStudentWork extends Model {}
CourseStudentWork.init({
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  course_id: DataTypes.BIGINT,
  story_id: DataTypes.BIGINT,
  student_id: DataTypes.BIGINT,
  submit_id: DataTypes.BIGINT,
  submit_name: DataTypes.STRING,
  teamwork: DataTypes.BOOLEAN,
  objective: DataTypes.BOOLEAN,
  mysql: DataTypes.BOOLEAN,
  group_id: DataTypes.BIGINT,
  contribution: DataTypes.DECIMAL(11,2),
  answer_json: DataTypes.TEXT,
  file_name: DataTypes.TEXT,
  file_url: DataTypes.TEXT,
  scrap_url: DataTypes.TEXT,
  scrap_json: DataTypes.TEXT,
  score: DataTypes.DECIMAL(11,2),
  score_by: DataTypes.BIGINT,
  score_time: DataTypes.DATE,
  team_score: DataTypes.DECIMAL(11,2),
  status: DataTypes.BOOLEAN,
  content: DataTypes.TEXT,
  round: DataTypes.INTEGER,
  last_one: DataTypes.BOOLEAN,
  aspose_ok: DataTypes.BOOLEAN,
  aspose_status: DataTypes.STRING,
  aspose_time: DataTypes.DATE,
  aspose_error: DataTypes.STRING,
  like_count: DataTypes.INTEGER,
  favorite_count: DataTypes.INTEGER,
  create_time: DataTypes.DATE,
  update_time: DataTypes.DATE,
  deleted: DataTypes.BOOLEAN,
  tenant_id: DataTypes.BIGINT,
  recommend: DataTypes.BOOLEAN,
  recommend_rank: DataTypes.INTEGER,
  dept_name: DataTypes.STRING,
  group_name: DataTypes.STRING
}, { sequelize, modelName: 'courseStudentWork', tableName: 'course_student_work', timestamps: false });
module.exports = CourseStudentWork;
