const { DataTypes, Model } = require('sequelize');
const sequelize = require('../config/database');
class Story extends Model {}
Story.init({
  id: { type: DataTypes.BIGINT, primaryKey: true, autoIncrement: true },
  super_id: DataTypes.BIGINT,
  course_id: DataTypes.BIGINT,
  goal_id: DataTypes.BIGINT,
  // 课程地图：史诗 & 阶段关联
  epic_id: DataTypes.BIGINT,
  release_id: DataTypes.BIGINT,
  story_name: DataTypes.STRING,
  story_desc: DataTypes.TEXT,
  story_type: DataTypes.INTEGER,
  preset: DataTypes.STRING,
  max_contribute: DataTypes.INTEGER,
  min_contribute: DataTypes.INTEGER,
  required: DataTypes.BOOLEAN,
  total_score: DataTypes.DECIMAL(11,2),
  difficulty: DataTypes.INTEGER,
  allow_file: DataTypes.STRING,
  file_size: DataTypes.INTEGER,
  auto_rename: DataTypes.BOOLEAN,
  file_name: DataTypes.STRING,
  max_submit: DataTypes.INTEGER,
  submit_type: DataTypes.INTEGER,
  unlock_type: DataTypes.INTEGER,
  prev_story_id: DataTypes.BIGINT,
  prev_release_id: DataTypes.BIGINT,
  start_time: DataTypes.DATE,
  end_time: DataTypes.DATE,
  examine_type: DataTypes.INTEGER,
  enable_rules: DataTypes.BOOLEAN,
  llm_status: DataTypes.BOOLEAN,
  prompt: DataTypes.TEXT,
  visible_groups: DataTypes.TEXT,
  pid: DataTypes.BIGINT,
  copy_id: DataTypes.BIGINT,
  qna: DataTypes.TEXT,
  mysql_link: DataTypes.STRING,
  video_link: DataTypes.STRING,
  video_type: DataTypes.INTEGER,
  version_status: DataTypes.INTEGER,
  version: DataTypes.BIGINT,
  repo_id: DataTypes.BIGINT,
  repo_switch: DataTypes.INTEGER,
  repo_version: DataTypes.BIGINT,
  style: DataTypes.TEXT,
  sort: DataTypes.INTEGER,
  position_x: DataTypes.INTEGER,
  position_y: DataTypes.INTEGER,
  creator: DataTypes.STRING,
  create_time: DataTypes.DATE,
  updater: DataTypes.STRING,
  update_time: DataTypes.DATE,
  deleted: DataTypes.BOOLEAN,
  tenant_id: DataTypes.BIGINT
}, { sequelize, modelName: 'story', tableName: 'course_map_story', timestamps: false });
module.exports = Story;
