
CREATE TABLE `course_group`  (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `course_id` BIGINT NULL DEFAULT NULL COMMENT '课堂ID',
  `group_name` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '小组名称',
  `max_size` INT NULL DEFAULT NULL COMMENT '最大人数',
  `current_size` INT NULL DEFAULT NULL COMMENT '当前人数',
  `group_code` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '小组码',
  `sort` INT NULL DEFAULT NULL COMMENT '排序',
  `dept_id` BIGINT NULL DEFAULT NULL COMMENT '组织ID(数据权限)',
  `user_id` BIGINT NULL DEFAULT NULL COMMENT '用户ID(数据权限)',
  `creator` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 10000 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '课堂小组表' ROW_FORMAT = DYNAMIC;

SET FOREIGN_KEY_CHECKS = 1;
