
CREATE TABLE `course_map_story`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `super_id` bigint NULL DEFAULT NULL COMMENT '来源的ID',
  `course_id` bigint NULL DEFAULT NULL COMMENT '授课ID',
  `goal_id` bigint NULL DEFAULT NULL COMMENT '目标ID',
  `epic_id` bigint NULL DEFAULT NULL COMMENT '史诗ID',
  `release_id` bigint NULL DEFAULT NULL COMMENT '发布ID',
  `story_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '任务名称',
  `story_desc` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '任务描述',
  `story_type` int NULL DEFAULT NULL COMMENT '任务类型 1=个人 2=团队(队长提交) 3=团队(全员提交) 4 客观题 5 任务组 6 预留 7 视频课 8 主观题（简答题） 9 mysql题',
  `preset` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '任务形式预设编码',
  `max_contribute` int NULL DEFAULT NULL COMMENT '团队任务最大贡献度',
  `min_contribute` int NULL DEFAULT 0 COMMENT '团队任务最小贡献度',
  `required` bit(1) NULL DEFAULT NULL COMMENT '是否是必做任务',
  `total_score` decimal(11, 2) NULL DEFAULT NULL COMMENT '满分',
  `difficulty` int NULL DEFAULT NULL COMMENT '任务难易程度 1-5分 1=易 5=难',
  `allow_file` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '可提交的文件格式',
  `file_size` int NULL DEFAULT NULL COMMENT '文件大小M',
  `auto_rename` bit(1) NULL DEFAULT NULL COMMENT '是否自动重命名',
  `file_name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '文件名格式',
  `max_submit` int NULL DEFAULT NULL COMMENT '作业最多可提交几次 0=不限制',
  `submit_type` int NULL DEFAULT NULL COMMENT '作业提交方式 0=无需提交作业 1=课程结束前随时提交 2=任务时间范围内提交',
  `unlock_type` int NULL DEFAULT NULL COMMENT '任务解锁方式 0=不上锁 1=前置完成 2=前阶段完成 3=到达任务开始时间后',
  `prev_story_id` bigint NULL DEFAULT NULL COMMENT '前置任务ID',
  `prev_release_id` bigint NULL DEFAULT NULL COMMENT '前置阶段ID',
  `start_time` datetime NULL DEFAULT NULL COMMENT '任务开始时间',
  `end_time` datetime NULL DEFAULT NULL COMMENT '任务结束时间',
  `examine_type` int NOT NULL COMMENT '批作业设置 1=无特殊设置 2=分配指定教师',
  `enable_rules` bit(1) NULL DEFAULT b'0' COMMENT '是否开启批改规则',
  `llm_status` bit(1) NULL DEFAULT b'0' COMMENT '是否开启ai批改',
  `prompt` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '提示词',
  `required_count` int NULL DEFAULT NULL COMMENT '任务组的需要完成任务数',
  `visible_groups` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '可见的小组id，逗号分隔',
  `pid` bigint NULL DEFAULT NULL COMMENT '任务组的id（父任务id）',
  `copy_id` bigint NULL DEFAULT NULL COMMENT '复制的id',
  `qna` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '题目和答案json（type=9使用，客观题不使用）',
  `mysql_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT 'sql文件链接（type=9使用）',
  `video_link` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '视频课的url或AI课id',
  `video_type` int NULL DEFAULT NULL COMMENT '0 是 AI课 1是视频',
  `version_status` int NULL DEFAULT NULL COMMENT '版本状态 0=最新 1=落后',
  `version` bigint NULL DEFAULT 1 COMMENT '版本号',
  `repo_id` bigint NULL DEFAULT NULL COMMENT '原任务id',
  `repo_switch` int NULL DEFAULT NULL COMMENT '是否推送更新 0=否 1=是',
  `repo_version` bigint NULL DEFAULT NULL COMMENT 'repo版本号',
  `style` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '样式',
  `sort` int NULL DEFAULT NULL COMMENT '排序',
  `position_x` int NULL DEFAULT NULL COMMENT '横坐标',
  `position_y` int NULL DEFAULT NULL COMMENT '纵坐标',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`, `examine_type`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7089 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '课程地图-任务' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
